"""
Custom Claim Feature Builder
============================
Turns a single custom claim dict into the exact model feature row used by
src.ml.predict. It uses gold/inference_artifacts.json generated by run_gold.py.

This module is intentionally pure-Python/pandas-free for easy migration into a
FastAPI service, AWS Lambda container, ECS service, or Databricks model serving
wrapper. In the cloud phase, these local JSON lookups should become Databricks
Feature Store / Unity Catalog feature lookups.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from src.constants import (
    SENTINEL_MISSING,
    COL_AMOUNT_IMPUTED,
    COL_COST_MATCH_ENCODED,
    COL_COST_MATCH_LEVEL,
)

_REQUIRED_FEATURES: list[str] = [
    "diagnosis_code_missing",
    "procedure_code_missing",
    "billed_amount_missing",
    "proc_no_diag",
    "diag_no_proc",
    "billed_deviation_imputed_capped",
    "billed_amount_imputed",
    "log_billed_amount_imputed",
    "is_high_cost",
    "cost_match_encoded",
    "provider_claim_count",
    "provider_violation_rate",
    "patient_claim_count",
    "severity_rank",
    "specialty_encoded",
]


def _norm_code(value: Any) -> str:
    if value is None:
        return SENTINEL_MISSING
    text = str(value).strip().upper()
    if text == "" or text.lower() == "nan":
        return SENTINEL_MISSING
    return text


def _norm_text(value: Any, default: str = "Unknown") -> str:
    if value is None:
        return default
    text = str(value).strip()
    if text == "" or text.lower() == "nan":
        return default
    return text.title()


def _to_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        val = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(val):
        return None
    return val


def _clip(value: float | None, lower: float, upper: float) -> float | None:
    if value is None:
        return None
    return max(lower, min(upper, value))


class CustomClaimFeatureBuilder:
    """Builds model-ready feature rows for custom claims."""

    def __init__(self, artifacts: dict) -> None:
        self.artifacts = artifacts
        self.amount = artifacts.get("amount_imputation", {})
        self.cost = artifacts.get("cost", {})
        self.provider_history = artifacts.get("provider_history", {})
        self.patient_claim_counts = artifacts.get("patient_claim_counts", {})
        self.diagnosis_lookup = artifacts.get("diagnosis_lookup", {})
        self.specialty_map = artifacts.get("specialty_map", {})

    @classmethod
    def load(cls, gold_dir: Path) -> "CustomClaimFeatureBuilder":
        path = Path(gold_dir) / "inference_artifacts.json"
        if not path.exists():
            raise FileNotFoundError(f"Inference artifacts not found: {path}. Run run_gold.py first.")
        with open(path) as f:
            return cls(json.load(f))

    def _amount_features(self, procedure_code: str, billed_amount: float | None) -> tuple[float, str]:
        if billed_amount is not None and billed_amount >= 0:
            return billed_amount, "original"

        proc_medians = self.amount.get("procedure_medians", {})
        if procedure_code in proc_medians and proc_medians[procedure_code] is not None:
            return float(proc_medians[procedure_code]), "procedure_median"

        return float(self.amount.get("global_median", 0.0)), "global_median"

    def _cost_features(self, procedure_code: str, location: str) -> tuple[float | None, str, int]:
        regional_lookup = self.cost.get("regional_lookup", {})
        procedure_lookup = self.cost.get("procedure_lookup", {})
        encoding = self.cost.get("match_encoding", {"missing": 0, "procedure_avg": 1, "regional": 2})

        regional_key = f"{procedure_code}|{location}"
        if regional_key in regional_lookup and regional_lookup[regional_key].get("expected_cost") is not None:
            return float(regional_lookup[regional_key]["expected_cost"]), "regional", int(encoding.get("regional", 2))

        if procedure_code in procedure_lookup and procedure_lookup[procedure_code].get("expected_cost") is not None:
            return float(procedure_lookup[procedure_code]["expected_cost"]), "procedure_avg", int(encoding.get("procedure_avg", 1))

        return None, "missing", int(encoding.get("missing", 0))

    def build(self, claim: dict[str, Any]) -> dict[str, Any]:
        """
        Build one feature dict from custom claim input.

        Input should contain raw claim fields:
        claim_id, patient_id, provider_id, diagnosis_code, procedure_code,
        billed_amount, specialty, location.
        """
        claim_id = claim.get("claim_id")
        patient_id = str(claim.get("patient_id", "UNKNOWN_PATIENT"))
        provider_id = str(claim.get("provider_id", "UNKNOWN_PROVIDER"))

        diagnosis_code = _norm_code(claim.get("diagnosis_code"))
        procedure_code = _norm_code(claim.get("procedure_code"))
        billed_amount = _to_float(claim.get("billed_amount"))
        if billed_amount is not None and billed_amount < 0:
            billed_amount = None

        provider = self.provider_history.get(provider_id, {})
        location = _norm_text(claim.get("location", provider.get("location", "Unknown")))
        specialty = _norm_text(claim.get("specialty", provider.get("specialty", "Unknown")))

        diagnosis_missing = diagnosis_code == SENTINEL_MISSING
        procedure_missing = procedure_code == SENTINEL_MISSING
        amount_missing = billed_amount is None
        proc_no_diag = (not procedure_missing) and diagnosis_missing
        diag_no_proc = (not diagnosis_missing) and procedure_missing

        amount_imputed, amount_strategy = self._amount_features(procedure_code, billed_amount)
        expected_cost, cost_match_level, cost_match_encoded = self._cost_features(procedure_code, location)

        if expected_cost is not None and expected_cost > 0:
            deviation = (amount_imputed - expected_cost) / expected_cost * 100
            deviation_capped = _clip(deviation, -100.0, 500.0)
        else:
            deviation = None
            deviation_capped = None

        expected_cost_p75 = float(self.cost.get("expected_cost_p75", 0.0))
        is_high_cost = int(expected_cost_p75 > 0 and amount_imputed > expected_cost_p75)

        diag_meta = self.diagnosis_lookup.get(diagnosis_code, {})
        severity_rank = int(diag_meta.get("severity_rank", 0) or 0)

        features = {
            "claim_id": claim_id,
            "patient_id": patient_id,
            "provider_id": provider_id,
            "diagnosis_code": diagnosis_code,
            "procedure_code": procedure_code,
            "billed_amount": billed_amount,
            "specialty": specialty,
            "location": location,
            "amount_imputation_strategy": amount_strategy,
            COL_COST_MATCH_LEVEL: cost_match_level,
            "diagnosis_code_missing": bool(diagnosis_missing),
            "procedure_code_missing": bool(procedure_missing),
            "billed_amount_missing": bool(amount_missing),
            "proc_no_diag": bool(proc_no_diag),
            "diag_no_proc": bool(diag_no_proc),
            "billed_deviation_imputed_pct": None if deviation is None else round(float(deviation), 4),
            "billed_deviation_imputed_capped": deviation_capped,
            COL_AMOUNT_IMPUTED: float(amount_imputed),
            "log_billed_amount_imputed": float(math.log1p(max(amount_imputed, 0.0))),
            "is_high_cost": is_high_cost,
            COL_COST_MATCH_ENCODED: int(cost_match_encoded),
            "provider_claim_count": int(provider.get("provider_claim_count", 0) or 0),
            "provider_violation_rate": float(provider.get("provider_violation_rate", 0.0) or 0.0),
            "patient_claim_count": int(self.patient_claim_counts.get(patient_id, 0) or 0),
            "severity_rank": severity_rank,
            "specialty_encoded": int(self.specialty_map.get(specialty, 0) or 0),
        }

        for name in _REQUIRED_FEATURES:
            features.setdefault(name, None)

        return features

    def build_features(self, claim: dict[str, Any]) -> dict[str, Any]:
        """Backward/forward-compatible method name used by services and APIs."""
        return self.build(claim)


# Backward-compatible alias. Some earlier patches imported ClaimFeatureBuilder.
ClaimFeatureBuilder = CustomClaimFeatureBuilder
